DATASET:
  path: ""
  LIST:
    train: "train_PennFudanPed.odgt"
    val: "val_PennFudanPed.odgt"

MODEL:
  arch: "fasterrcnn_resnet50_fpn"

TRAIN:
  path: ""
  seed: -1
  DATA:
    batch_size: 4
    num_workers: 4
    disp_iter: 20
  LEN:
    num_epoch: 10
    start_epoch: 0
    early_stop: 4
  OPTIM:
    optim: "sgd"
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
  LR:
    schedule: 'step'
    step_size: 3
    gamma: 0.1