DATASET:
  root_dataset: "data/sets/PennFudanPed"
  list_train: "data/sets/PennFudanPed"
  list_val: "data/sets/PennFudanPed"
  num_classes: 2

MODEL:
  arch: "maskrcnn_resnet50_fpn"

TRAIN:
  batch_size: 1
  num_epoch: 10
  start_epoch: 0
  optim: "SGD"
  momentum: 0.9
  weight_decay: 0.0005
  lr: 0.005
  lr_step_size: 3
  lr_gamma: 0.1
  early_stop: 1
  num_workers: 4
  disp_iter: 10
  seed: 42

VAL:
  batch_size: 1
  checkpoint: "weights_best.pth"

TEST:
  checkpoint: "weights_best.pth"
  result: "./results"

DIR: "ckpt/maskrcnn_resnet50_fpn-pennfudan"