DATASET:
  root_dataset: "data/sets/PennFudanPed"
  list_train: "data/sets/PennFudanPed/train_PennFudanPed.odgt"
  list_val: "data/sets/PennFudanPed/val_PennFudanPed.odgt"
  num_classes: 2
  image_max_size: 720

MODEL:
  arch: "retinanet_resnet50_fpn"

TRAIN:
  batch_size: 32
  num_epoch: 10
  start_epoch: 0
  optim: "SGD"
  momentum: 0.9
  weight_decay: 0.0005
  lr: 0.005
  lr_step_size: 3
  lr_gamma: 0.1
  early_stop: 2
  num_workers: 4
  disp_iter: 10
  seed: ''

VAL:
  batch_size: 1
  checkpoint: "weights_best.pth"

TEST:
  checkpoint: "weights_best.pth"
  result: "./results"

DIR: "ckpt/retinanet_resnet50_fpn-pennfudanped"